### ISSUE TITLE
Rails >6.1 support

### ISSUE THREAD

**Issue by stereodenis** [aarona/devise_jwt_auth#7]
Now it
```
  s.add_dependency 'rails', '>= 4.2.0', '< 6.1'
```

**Comment by aarona** [comment]
I can take a look at this today and get a new version this week.

**Comment by stereodenis** [comment]
@aarona cool! Will wait for it

**Comment by aarona** [comment]
Ok after some more research, I've discovered that minitest-rails has not finished updating for rails 7 and thats required for testing the gem. You'll have to sit tight for a while, @stereodenis until they are ready. I'll keep monitoring this and when everything is ready, I'll push a release. Thanks for bringing my attention to this!

**Comment by stereodenis** [comment]
@aarona maybe, we can just update gem for using on >6.1 and <7. What do you think?

**Comment by aarona** [comment]
This gem has been updated to support Rails 6.1.4.4+. I having trouble getting OmniAuth tests to pass so no guarantee those will work with this version. I don't use OmniAuth with the project I'm currently using this gem with but if you'd like to take a stab at that issue, you're welcome to.
