### ISSUE TITLE
Refresh token cookie path from config

### ISSUE THREAD

**Issue by stereodenis** [aarona/devise_jwt_auth#9]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/1406461/154318850-02b68db1-8493-4cbd-a8f6-8ba742fc8fde.png">

**Comment by aarona** [comment]
Is this currently causing you an issue? Do you need to override this?

**Comment by stereodenis** [comment]
Yep, I'm using "/users" path

Also, I don't understand why this gem use cookies for authorization?

**Comment by stereodenis** [comment]
Cookie is not setting. Maybe, because I use api url /api/v1/auth/refresh_token

<img width="1594" alt="image" src="https://user-images.githubusercontent.com/1406461/154448898-7ad1a871-1411-4d16-8f2a-8e86f14c331d.png">
